# Generated by Django 2.0 on 2017-12-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0003_auto_20171230_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
