# Generated by Django 2.0 on 2017-12-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0004_auto_20171231_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/jpeg/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/jpeg/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/jpeg/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/jpeg/', width_field='width_field'),
        ),
    ]
