# Generated by Django 2.0 on 2017-12-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0005_auto_20171231_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='urlembed',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/jpeg/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/jpeg/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/jpeg/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/jpeg/', width_field='width_field'),
        ),
    ]
