# Generated by Django 2.0 on 2017-12-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0007_auto_20171231_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yazi1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='yazi2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='yazi3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/jpeg/'),
        ),
    ]
