# Generated by Django 2.0 on 2017-12-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0009_remove_post_file1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
    ]
