# Generated by Django 2.0 on 2018-01-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0012_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email',
        ),
    ]
