# Generated by Django 2.0 on 2018-01-14 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messblog', '0013_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Posten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazi', models.TextField()),
                ('yazi1', models.TextField(blank=True, null=True)),
                ('yazi2', models.TextField(blank=True, null=True)),
                ('yazi3', models.TextField(blank=True, null=True)),
                ('yar_tarih', models.DateTimeField(default=django.utils.timezone.now)),
                ('yay_tarih', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/jpeg/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/jpeg/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/jpeg/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/jpeg/')),
                ('urlembed', models.URLField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/jpeg/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messblog.Categories')),
                ('tag', models.ManyToManyField(to='messblog.Tag')),
            ],
        ),
    ]
